### ISSUE TITLE
[BUG]: test

### ISSUE THREAD

**Issue by CatQueenCodes** [I3uckwheat/cards-of-carousal#278]
**Link Test Case Issue#:**

**Device used:**
**Browser(s) used:**

# Description

### Expected Behavior
Description

### Actual Behavior
Description

## Replication Steps & Data
Include step by step directions on how you found this bug. Include the specific data inputs you used.

## Acceptance criteria:
- Copy over the "Completion Criteria" check boxes for the device/browser you are using from the test case and paste it in place of this bullet (or accessibility checkboxes if this is an accessibility bug).
- [ ] Add to the "Triage" category in the [Bugs/Refactor Kanban](https://github.com/I3uckwheat/cards-of-carousal/projects/2)
- [ ] Add the "Bug" tag (and the "Accessibility Bug" tag if necessary)
- [ ] Link this issue to your pull request.

## Important
- [ ] Please ping CatQueen/Grace in the #QA channel in discord once you make a PR for this bug so I can open another test case ticket for it, so it can be retested to ensure it works post fix.

**Comment by I3uckwheat** [comment]
@CatQueenCodes Can we close this?

**Comment by CatQueenCodes** [comment]
> @CatQueenCodes Can we close this?

Yep! Sorry!
